In [ ]:
import pandas as pd
df = pd.read_csv('orders_sample.csv')
print(df)

In [52]:
df.to_csv('new_file.csv', index=False)

In [50]:
df.groupby('Category')['Shipped'].value_counts()
(df['Shipped']=='Yes').groupby(df['Category']).sum()

Category
Accessories        1
Electronics        4
Furniture          1
Home & Kitchen     0
Home Appliances    0
Stationery         1
Name: Shipped, dtype: int64

In [36]:
df.loc[(df['CustomerName'].str.startswith('A')) | (df['Quantity']==1)]

,OrderID,CustomerName,Product,Category,Quantity,Price,OrderDate,Shipped,Country
0,1001,Aarav Sharma,Laptop,Electronics,1,65000,01-05-2026,Yes,India
4,1005,Kabir Mehta,Coffee Maker,Home Appliances,1,4200,07-05-2026,No,India
5,1006,Ananya Rao,Smartphone,Electronics,1,32000,08-05-2026,Yes,India
8,1009,Aditya Jain,Desk Lamp,Furniture,2,950,12-05-2026,Yes,India
9,1010,Meera Nair,Tablet,Electronics,1,28000,15-05-2026,Yes,India

In [31]:
df[df['Shipped']=='Yes']
df[df['CustomerName'].str.startswith('A')]

,OrderID,CustomerName,Product,Category,Quantity,Price,OrderDate,Shipped,Country
0,1001,Aarav Sharma,Laptop,Electronics,1,65000,01-05-2026,Yes,India
5,1006,Ananya Rao,Smartphone,Electronics,1,32000,08-05-2026,Yes,India
8,1009,Aditya Jain,Desk Lamp,Furniture,2,950,12-05-2026,Yes,India

In [26]:
print(list(df.iloc[0])[0])
print(df.iloc[0]['Product'])

1001
Laptop

In [ ]:
a=dict(df[['Product','Category']])
b=list(a.values())
#print(b)
print(b[0])
print(b[1])

0        Electronics
1          Furniture
2        Electronics
3         Stationery
4    Home Appliances
5        Electronics
6        Accessories
7     Home & Kitchen
8          Furniture
9        Electronics
Name: Category, dtype: str

In [6]:
dict(zip(df['Product'], df['Category']))

{'Laptop': 'Electronics',
 'Office Chair': 'Furniture',
 'Headphones': 'Electronics',
 'Notebook': 'Stationery',
 'Coffee Maker': 'Home Appliances',
 'Smartphone': 'Electronics',
 'Backpack': 'Accessories',
 'Water Bottle': 'Home & Kitchen',
 'Desk Lamp': 'Furniture',
 'Tablet': 'Electronics'}

In [ ]:
df.index

In [ ]:
df.columns

In [ ]:
df.describe()

In [ ]:
df.info()

In [ ]:
df.tail(5)

In [ ]:
df.head(5)